### ISSUE TITLE
[W::dhtslib.tagvalue.TagValue.this] SA doesn't exist for this record & rs doesn't exist for this record

### ISSUE THREAD

**Issue by xiaotiqingzz** [blachlylab/fade#12]
- First, I mapping reads into genome: bwa mem -M -R "@RG\tID:Sample\tLB:Sample\tSM:Sample\tPL:ILLUMINA" -t 30 hg19.fa Sample.R1.paired.fastq.gz Sample.R2.paired.fastq.gz > Sample.sam

- Next, sort the sam file into bam, and use picard mark duplicates reads,  gatk realign indel, I get  Sample.realigned.bam

- Then, I run the command as your recommend: fade annotate -b Sample.realigned.bam hg19.fa > Sample.realigned.anno.bam, **I get the WARNING "[W::dhtslib.tagvalue.TagValue.this] SA doesn't exist for this record" full of my screen**, but I stall get Sample.realigned.anno.bam

- Finally,  I skip the sort steps run: fade out -b Sample.realigned.anno.bam > Sample.realigned.anno.filter.bam, the command exit and output error: 
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::dhtslib.tagvalue.TagValue.this] rs doesn't exist for this record
core.exception.AssertError@../../.dub/packages/dhtslib-0.10.1/dhtslib/source/dhtslib/tagvalue.d(84): Assertion failure
----------------
??:? [0x55b3d5efe590]
??:? [0x55b3d5f0884a]
??:? [0x55b3d5eef80d]
??:? [0x55b3d5ee722c]
.......

I want to know what's going on? ?

**Comment by charlesgregory** [comment]
This appears to be a combination of two issues. A bug and the fact that I uploaded a debug build of the program as a release (I assume you are using the v0.1.0 release binary). The debug version will issue warnings if it tries to pull a tagvalue that doesn't exist, even though we have code to deal with that case. The release version silences these warnings. The second assertion error is actually a bug that I am currently fixing.

**Comment by charlesgregory** [comment]
@xiaotiqingzz I have posted a [release](https://github.com/blachlylab/fade/releases/tag/v0.1.1) with a new binary. Could you see if this fixes the issue?

**Comment by xiaotiqingzz** [comment]
I download the fade ( Version 0.1.1 ),  and it works very will !
NO WARNING of "[W::dhtslib.tagvalue.TagValue.this] SA doesn't exist for this record"
NO ERROR of "[W::dhtslib.tagvalue.TagValue.this] rs doesn't exist for this record"
Thank your for fix my problem : )

**Comment by jblachly** [comment]
@xiaotiqingzz Thank you; please let us know how the tool is working in production for you.

Kind regards
