### ISSUE TITLE
ab:z tag conflicting with samfile format

### ISSUE THREAD

**Issue by kristin-watchmaker** [blachlylab/fade#19]
I've been having issues with the ab:z tag introducing new line characters in the sam file. This hinders downstream analysis and disallows file parsing using samtools in some instances. These discrepancies are present in the sam files (mostly kappa sonicated libraries) deposited in SRA from your article published in NAR genomics and bioinformatics. Although, none of the new line characters in these SRA files interfere with samtools.

**Comment by charlesgregory** [comment]
Yes it is probably due to that tag being raw base quality scores as opposed to phred-scaled. I neglected to notice this as we mostly use the bam format. I will get a fix and new release to address this soon.

**Comment by charlesgregory** [comment]
This issue was closed via my commit. I have made a new release with a new binary that should fix the issue. Please let me know and reopen if this doesn't fix the issue or if you have any other issues.

**Comment by charlesgregory** [comment]
I have also updated the docker image now in case you were using fade via docker.

**Comment by kristin-watchmaker** [comment]
Hi Charles

The update did not seem to fix the issue. I've uploaded a screenshot of the new line introduced into the sam file after FADE annotation (first image). I also noticed another issue where an rs:i:33 tag is being placed on samfile records (image 2). I don't think this is intentional?  If it would be easier, I can provide the bam file in question. These two issues are showing up in ALL of my bam files (a dozen or so), but not in any your sam files deposited into SRA that I've checked (I've only checked 10 of your SRA files).

<img width="1139" alt="Screen Shot 2021-07-26 at 10 49 15 AM" src="https://user-images.githubusercontent.com/84340423/127027826-f1c655a6-f03f-4384-b9cb-1cb1b8918019.png">


<img width="1143" alt="Screen Shot 2021-07-26 at 10 56 41 AM" src="https://user-images.githubusercontent.com/84340423/127028717-ee023114-9b24-4b51-bc43-35ff5429dde4.png">

**Comment by charlesgregory** [comment]
I see, that is troubling. If you could provide the original sam/bam file (or at least the portion that causes the error + the header) that produces the error that would be great!

**Comment by charlesgregory** [comment]
Just to clarify the tags you are seeing, the `rs`, `am`, `as`, `ar`, and `ab` tags are added by fade during the annotate step. `rs` is a binary flag and shows up as a number. These tags are then used later to determine artifact status and either clip or remove the reads. `rs:i:33` would indicate a read has: softclipping, and a supplementary alignment, though no detected artifact. This [description](https://github.com/blachlylab/fade/blob/master/TAGS.md) is a bit out of date but somewhat describes the tags.

**Comment by kristin-watchmaker** [comment]
I have attached a bam file which contains a subset of 10000 samfile lines
(with headers) which produce the newline error after fade annotation.

**Comment by charlesgregory** [comment]
> I have attached a bam file which contains a subset of 10000 samfile lines
(with headers) which produce the newline error after fade annotation.

If you attached it via email as a response to this github issue it won't come through, though you can post it directly on github by clicking the bottom of the comment window and attaching the file.

**Comment by kristin-watchmaker** [comment]
# #
Duplicate of #

**Comment by kristin-watchmaker** [comment]
[WMG_subset_10000.bam.gz](https://github.com/blachlylab/fade/files/6896387/WMG_subset_10000.bam.gz)

**Comment by charlesgregory** [comment]
Using your provided bam file, I am encountering the issue with fade version v0.3.0. Though using the newest version of fade (v0.3.6) installed via conda/bioconda or the most recent binary (v0.3.1 downloaded [here](https://github.com/blachlylab/fade/releases/download/v0.3.1/fade)) doesn't produce the issue.

Are you sure you are using the most up-to-date fade version? Are you using the docker image? It's possible I may not have updated the image correctly on dockerhub.

**Comment by charlesgregory** [comment]
Actually just checked the docker image and it appears to be up-to-date to v0.3.1 as well.

**Comment by kristin-watchmaker** [comment]
I thought I was using the most up-to-date binary version published on GitHub. I'll try again!
