### ISSUE TITLE
Exception when adding the bam tag.

### ISSUE THREAD

**Issue by yangyxt** [blachlylab/fade#22]
I run into this error when simpy trying to run fade annotate.
Here is the error log as a screenshot:
![image](https://user-images.githubusercontent.com/40780228/144352315-ed1a875e-c162-49ab-8c21-d5667d22d9d5.png)

I use GATK ValidateSamFile to check the integrity of BAM file before using them on FADE. So I'm pretty confident my BAM file is not corrupted.

**Comment by charlesgregory** [comment]
Yes I agree, this doesn't sound like an issue with your bam file. I think I have run into this issue before on a prior version of fade. 

Could you try our new 0.5.1 version? It think it should solve this issue. I have uploaded a x86_64 static linux binary to the release.

**Comment by charlesgregory** [comment]
Continuing from https://github.com/blachlylab/fade/issues/21#issuecomment-1002956965.

I did observe this behavior, though it should be corrected. I can no longer recreate this error with the new 0.5.2 binary and my test data. Would it be possible for you to provide a sample of your bam file that produces the issue so I can reproduce it and perform testing?

**Comment by charlesgregory** [comment]
Actually that may not be necessary yet. I have managed to recreate the error. I will investigate the source of the error.

**Comment by charlesgregory** [comment]
@yangyxt, I have now added another release, v0.5.3. I specifically was able to recreate the issue you observed and create a solution. I have also fixed another crash that was occurring randomly. Could you please try the 0.5.3 release? I appreciate and thank you for your patience through this process. 

You may see this appear in the log from fade v0.5.3:
```
[I::dhtslib.sam.record.SAMRecord.opIndexAssign!ubyte.opIndexAssign] Undefined issue adding/updating bam tag. Trying again...
```
This message just indicates that the bug was hit and we are running the work-around for it, but it is not an error.

**Comment by yangyxt** [comment]
> @yangyxt, I have now added another release, v0.5.3. I specifically was able to recreate the issue you observed and create a solution. I have also fixed another crash that was occurring randomly. Could you please try the 0.5.3 release? I appreciate and thank you for your patience through this process.
> 
> You may see this appear in the log from fade v0.5.3:
> 
> ```
> [I::dhtslib.sam.record.SAMRecord.opIndexAssign!ubyte.opIndexAssign] Undefined issue adding/updating bam tag. Trying again...
> ```
> 
> This message just indicates that the bug was hit and we are running the work-around for it, but it is not an error.

Thank you for the improvement. I'll try it now.

**Comment by yangyxt** [comment]
> @yangyxt, I have now added another release, v0.5.3. I specifically was able to recreate the issue you observed and create a solution. I have also fixed another crash that was occurring randomly. Could you please try the 0.5.3 release? I appreciate and thank you for your patience through this process.
> 
> You may see this appear in the log from fade v0.5.3:
> 
> ```
> [I::dhtslib.sam.record.SAMRecord.opIndexAssign!ubyte.opIndexAssign] Undefined issue adding/updating bam tag. Trying again...
> ```
> 
> This message just indicates that the bug was hit and we are running the work-around for it, but it is not an error.

I just tried and it seems worked. The logging info are pasted below:
![image](https://user-images.githubusercontent.com/40780228/147953857-f031881f-6aec-46c5-b9a7-9dde51cc8810.png)

**Comment by charlesgregory** [comment]
Yep looks good. I will close this now. If you see anymore errors or have any issues, please open an issue. Thank you for helping us find this and for using fade!
