### ISSUE TITLE
Warning or error log in fade annotate  ?

### ISSUE THREAD

**Issue by xiucz** [blachlylab/fade#31]
Hi, 
Thanks for your tool, when I test it for my panel data, it shows following log, should I ignore it?

**Version: [fade.many-linux-x86_64.tar.gz](https://github.com/blachlylab/fade/releases/download/v0.6.0/fade.many-linux-x86_64.tar.gz)**

```
fade annotate -t 8 -b $filein $ref_hsa > test.fadeanno.1.bam
```
Here is the log on screen:
```
[W::fade annotate] Output SAM/BAM will not be sorted (regardless of prior sorting)
[I::dhtslib.sam.reader.SAMReader.__ctor!string.this] 6 CPU cores detected; enabling multithreading
[I::dhtslib.sam.writer.SAMWriter.__ctor!(File).this] 6 CPU cores detected; enabling multithreading
[W::dparasail.alignment.Parasail.this] Couldn't load matrix named ACTGN, assuming alphabet
[W::dparasail.alignment.Parasail.this] Attempting to create matrix from alphabet ACTGN
[I::dhtslib.sam.record.SAMRecord.opIndexAssign!ubyte.opIndexAssign] Undefined issue adding/updating bam tag. Trying again...
[I::dhtslib.sam.record.SAMRecord.opIndexAssign!ubyte.opIndexAssign] Undefined issue adding/updating bam tag. Trying again...
[I::dhtslib.sam.record.SAMRecord.opIndexAssign!ubyte.opIndexAssign] Undefined issue adding/updating bam tag. Trying again...
[I::dhtslib.sam.record.SAMRecord.opIndexAssign!ubyte.opIndexAssign] Undefined issue adding/updating bam tag. Trying again...
[I::dhtslib.sam.record.SAMRecord.opIndexAssign!ubyte.opIndexAssign] Undefined issue adding/updating bam tag. Trying again...
[I::dhtslib.sam.record.SAMRecord.opIndexAssign!ubyte.opIndexAssign] Undefined issue adding/updating bam tag. Trying again...
[I::dhtslib.sam.record.SAMRecord.opIndexAssign!ubyte.opIndexAssign] Undefined issue adding/updating bam tag. Trying again...
[I::dhtslib.sam.record.SAMRecord.opIndexAssign!ubyte.opIndexAssign] Undefined issue adding/updating bam tag. Trying again...
```
Best,
xiucz

**Comment by charlesgregory** [comment]
This is an issue that occurs rarely when fade is modifying the bam tags on a bam file. The message you see is just an indicator that the error occurred and it tries again to modify the tag. The issue in full is discussed over on [`dhtslib`](https://github.com/blachlylab/dhtslib) in issue https://github.com/blachlylab/dhtslib/issues/127. I am not sure if the true problem resides in `fade`, [`dhtslib`](https://github.com/blachlylab/dhtslib) or [`htslib`](https://github.com/samtools/htslib) as it is difficult to re-create outside of the setting of running fade. 

The message is just a indicator for future debugging.

**Comment by xiucz** [comment]
@charlesgregory 
Thank you , I will close this issue.
